apiVersion: v1
kind: Service
metadata:
  labels:
    app: vink
    service: vink
  name: vink
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vink
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: grpc
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: grpc-web
    port: 8080
    protocol: TCP
    targetPort: 8080
