apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "cdi.crUninstallHook.name" . }}
  {{ template "cdi.crUninstallHook.annotations" (dict "hookWeight" 1) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cdi.crUninstallHook.name" . }}
  {{ template "cdi.crUninstallHook.annotations" (dict "hookWeight" 1) }}
rules:
  - apiGroups: [ "cdi.kubevirt.io" ]
    resources: [ "cdis" ]
    verbs: [ "*" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cdi.crUninstallHook.name" . }}
  {{ template "cdi.crUninstallHook.annotations" (dict "hookWeight" 2) }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.namespace }}
    name: {{ template "cdi.crUninstallHook.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "cdi.crUninstallHook.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "cdi.crUninstallHook.name" . }}
  {{ template "cdi.crUninstallHook.annotations" (dict "hookWeight" 3) }}
spec:
  template:
    metadata:
      name: {{ template "cdi.crUninstallHook.name" . }}
    spec:
      serviceAccountName: {{ template "cdi.crUninstallHook.name" . }}
      restartPolicy: {{ .Values.hookRestartPolicy }}
      containers:
        - name: {{ template "cdi.crUninstallHook.name" . }}
          image: {{ .Values.hookImage }}
          securityContext:
            {{- toYaml .Values.hookSecurityContext | nindent 12 }}
          command: [ "/bin/bash", "-c" ]
          args:
            - >
              echo '[INFO] Deleting cdi resources...';
              kubectl delete cdi --wait --all --ignore-not-found;

              echo '[INFO] Waiting for cdi to be fully deleted...';
              kubectl wait --for=delete cdis.cdi.kubevirt.io/cdi;

              echo '[INFO] Waiting for the CDI API server deployment to be deleted...';
              kubectl wait --for=delete deployments/cdi-apiserver;

              echo '[INFO] Waiting for the CDI deployment to be deleted...';
              kubectl wait --for=delete deployments/cdi-deployment;

              echo '[INFO] Waiting for the CDI upload proxy deployment to be deleted...';
              kubectl wait --for=delete deployments/cdi-uploadproxy;

              echo '[INFO] All CDI resources and deployments deletion steps completed.';
